### ISSUE TITLE
shouldn`t be -0 the last item in the array?

### ISSUE THREAD

**Issue by rlech** [sindresorhus/negative-array#10]

**Comment by sindresorhus** [comment]
Can you provide an example of what you're asking?

**Comment by mtimofiiv** [comment]
As far as javascript is concerned...

```js
const testString = 'Why, hello there'
testString.slice(-1) //=> 'e'
```

So I believe the standard is there for starting negative lookups with `-1`. And since JS does not seem to consider a signed and unsigned version of a zero as different:

```js
0 === -0 //=> true
```

It's best to start at `-1`.

**Comment by SamVerschueren** [comment]
@sindresorhus What I guess he means is the following

```js
const array = ['foo', 'bar'];
console.log(array[-0]);
//=> 'bar'

console.log(array[-1]);
//=> foo
```

I'm 👎 on this as pointed out by @mtimofiiv, things like `slice`, `substring`, etc. all start with `-1` for negative lookups, `-0` is just weird.

**Comment by sindresorhus** [comment]
Yeah, not going to happen, for all of the above reasons.
